### ISSUE TITLE
Cannot find GPU memory type... Bye!

### ISSUE THREAD

**Issue by evlo** [enerc/VulkanXMRMiner#11]
Hi, I started the miner, configuration prompts did show, I filled it all up, I got to my last card and this happend.

```
Card:11  4 Compute Units/Stream Multiprocessors, using factor 880 (3520 threads), local size 16
Use this card [Y/n]?:
Number of Compute Units [4]:
Factor [880]:
Worksize [16]:

Cannot find GPU memory type... Bye!
```

12th gpu is rx570 with samsung, first card is rx580 with samsung

Miner release 0.3 on win 10 1709

No config file was saved.

Also the autodetect found 144 something, I guess gpus, on index 12 is intel, which obviously does not support vulcan, rig has only 12 amd gpus, not 144, dunno what is up with that.
Maybe it does not ignore gpus that still have records in windows registry but are ghosts?

**Comment by enerc** [comment]
Hi,
The scenario looks familiar on amd crimson drivers. It was solved by DDU latest adrenalin drivers (2019.x).
After updating the driver, run vulkaninfo.exe and check that it reports the correct number of cards. 
If the Intel card shows up during configuration, skip it. I had no luck with Intel cards so far, but might work on recent chipset.

**Comment by IronDusts** [comment]
Hello,
I got the same issue. I'm running on Fedora 28 with latest available kernel and latest available amdgpu driver. 

[root@localhost ~]# uname -r
4.20.16-100.fc28.x86_64
[root@localhost ~]# rpm -qa |grep -i amdgpu
xorg-x11-drv-amdgpu-18.1.0-1.fc28.x86_64

Are you sure it's old driver? And if it is where can I get a newer one? 
Thanks

**Comment by enerc** [comment]
Hello,
Check the config file under /etc/vulkan/icd.d. There should be only one file referring the amdvlk64.so, and check the api_version as well (look at the readme for example). I think you might need the pro version of amdgpu to get the vulkan driver, right?
There is one user reporting an issue were disabling Above 4G decoding in BIOS fixed it.

**Comment by IronDusts** [comment]
Hello,

I've installed the vulkan driver from here https://github.com/GPUOpen-Drivers/AMDVLK according to the instructions. This driver is made to work with both amdgpu and amdgpu-pro. 

Also had installed it before from the Fedora repo - same result. 

vulkaninfo command returns proper output and detects all my GPUs. 

The icd file is as follows:
[root@localhost build]# cat /etc/vulkan/icd.d/amd_icd64.json 
{
	"file_format_version": "1.0.0",
		"ICD": {
			"library_path": "/usr/lib64/amdvlk64.so",
			"api_version": "1.1.97"
		}
}

And still does not work. 

Are you sure it's the vulkan driver? 
I think since vulkaninfo returns proper output and detects all GPUs then from driver side everything should be OK. I mean the only valid parameter to check the driver is the vulcaninfo command, if it's displaying proper stuff then the driver should be OK. 

Thanks

**Comment by enerc** [comment]
Hello,

The driver from https://github.com/GPUOpen-Drivers/AMDVLK  does not work for me. I have all invalid results. The one from the standard repo works.
Try to use the amdvlk64.so that comes with your amdgpu-pro installation (should be in opt)
For the memory issue, try to disable "Above 4G decoding" in the BIOS. It helped user shimmervoid.

**Comment by evlo** [comment]
now with 0.4 and clean everything i get cannot "Allocated" gpu memory for gpu 0, which is intel.
Is thre some commandline or json config template somewhere so I can force miner not to use intel gpu?

**Comment by enerc** [comment]
Example with 2 cards if Intel is in slot0 and GPUs start at 1:
{
 "crypto" : "monero",
 "pool_address" : "pool:port",
 "wallet_address" : "xxxxxxxx",
 "pool_password" : "x",
 "debug_network" : "false",
 "console_listen_port" : "0",
 "console_refresh_rate" : "30",
 "cards" : [
  {
    "index"    : "1",
    "cu"       : "56",
    "factor"   : "64",
    "worksize" : "16",
    "mem_chunk": "2"
  },  
  {
    "index"    : "2",
    "cu"       : "14",
    "factor"   : "56",
    "worksize" : "16",
    "mem_chunk": "2"
  }  
 ]
}

Cryptos are  one of monero, wownero, aeon, turtlecoin
CU is the number of compute units / Stream processors
Factor is best at a multiple of 16 (AMD)/32 (Nvidia) so  CU x Factor x (2 for monero/wonero, 1 for aeon, and 0.25 for turtle) is below 8Gb and below card memory size
